### ISSUE TITLE
Migrate to PureScript 0.12

### ISSUE THREAD

**Issue by paluh** [Thimoteus/purescript-snail#1]
Hi @Thimoteus,

I've quite mechanically done (not extensively tested) migration of this project to PureScript 0.12:

https://github.com/Thimoteus/purescript-snail/compare/master...paluh:master

* It depends on newest version of `purescript-node-os` (this with updated deps which is not released yet).

* It depends on updated `purescript-coercible` version (though `coerce` is used only in single place).

I can update my fork and provide PR when we migrate these other libs of yours.

P.S.
It is a real shame that I've discovered it so late when I've already implemented a lot of similar stuff myself ;-)

**Comment by Thimoteus** [comment]
Sweet. What if we get rid of `coercible`, would that make things easier?

**Comment by paluh** [comment]
I can drop this dependency if you want to. To be honest I have nothing against `coercible` myself - it is just a bit mind bending what instances of `Coercible` we should provide in the core lib which would make it useful but also extensible.

So answering your question: it would be a little bit easier if we drop `coercible` because we don't have to solve `coercible` design issues before this next `purescript-snail` release.

**Comment by Thimoteus** [comment]
Yeah, let's do that then.

**Comment by paluh** [comment]
Ok!
