### ISSUE TITLE
`running-snail` - just an idea..

### ISSUE THREAD

**Issue by paluh** [Thimoteus/purescript-snail#4]
From my perspective scripting and server side daemon programming is usually not performance critical. I wonder if we can introduce for debugging / testing / "dry running" purposes `run` layer on top of existing primitives. Do you see any major problems along the way?
I understand that it is huge amount of work but I want to know your opinion on the topic @Thimoteus.

**Comment by Thimoteus** [comment]
I'm not sure I understand, do you mean something like `stack runghc -- Example.hs` for running a single file?

**Comment by paluh** [comment]
I thought about `purescript-run` and providing free algebra for every primitive from this lib so we can write scripts in an abstract form and provide an interpreter to `Aff` or to a simulated filesystem etc.
This should probably be separate project but I wonder if you would find it useful. In my own scenarios it seems relevant to be able to test some scripts without touching filesystem etc.

**Comment by paluh** [comment]
Closing this as I won't be able to experiment with this anytime soon.
